stages:
  - build
  - test

before_script:
  - pip install tox

build:
  image: python:3.7
  stage: build
  script:
    - python setup.py sdist bdist_wheel --universal
    - echo "What's in the package?"
    - tar -tvf dist/django-flickr-*tar.gz
    - unzip -l dist/django_flickr-*whl

test-py35:
  image: python:3.5
  stage: test
  script:
    - tox -e $(tox -ls | grep py35 | sed ':1;N;s/\n/,/;t1')

test-py36:
  image: python:3.6
  stage: test
  script:
    - tox -e $(tox -ls | grep py36 | sed ':1;N;s/\n/,/;t1')

test-py37:
  image: python:3.7
  stage: test
  script:
    - tox -e $(tox -ls | grep py37 | sed ':1;N;s/\n/,/;t1')
